### ISSUE TITLE
General branding

### ISSUE THREAD

**Issue by drnikko** [drupaldiversity/drupaldiversity.github.io#7]
We need to take the logo work performed in https://github.com/drupaldiversity/administration/issues/17 and update the website to use that logo.  

Of course, the website as a whole could use a facelift, but the logo is certainly the easiest place to start.

I'm kicking this to both devs and you can decide who can do it. :) 

Thank you for offering to help!!

**Comment by mikemiles86** [comment]
I did not realize the website is in Jekyll. I do not know Jekyll and do not want to be a bottle neck to this issue. It may be best to un-assign me.  Sorry! If I find some free time to learn Jekyll I'll be sure to jump on a task to help.

**Comment by cleverington** [comment]
## Update

Logo included in PR for SEO from #8.

Its not the greatest, but then I'm not a FE Guru.  =>^-^<=

**Comment by cleverington** [comment]
## Recommended Alteration

Should probably alter the PR slightly prior to approval to update our name to be `Drupal Diversity & Inclusion` instead of `Drupal Diversity`.

Since we're going to start being actively tracked via Webcrawlers with the completion of #8, we should probably be promoting the **right** terminology, based on recent naming convention decisions for the Workgroup.

**Comment by AlannaBurke** [comment]
Can we have a repo or folder in github with all of our branding materials? Logos, etc? (or is there one that I am missing?)

**Comment by drnikko** [comment]
@AlannaBurke yes for sure.  I think administration might make more sense? (But, you know, I'm making this stuff up as I go along...)

**Comment by drnikko** [comment]
@AlannaBurke https://github.com/drupaldiversity/administration/tree/master/assets

**Comment by cleverington** [comment]
## Update and Close

Assets created and the DD&I logo has been added to the site.
